### ISSUE TITLE
機能提案: テンプレートファイル一覧表示オプション --list 

### ISSUE THREAD

**Issue by macinjoke** [akameco/touch-alt#4]
機能の提案です。

`$ touch-alter --list (or -l)` でテンプレートファイルの一覧(`~/.touch-alt` の中身)が表示できる機能があれば便利ではないでしょうか。

```
$ touch-alter --list
license
.editorconfig
...
```

もし必要であれば作ってみたいです！

**Comment by akameco** [comment]
@macinjoke Welcome PRs.
