### ISSUE TITLE
誤ってファイル内容を消してしまう挙動について

### ISSUE THREAD

**Issue by macinjoke** [akameco/touch-alt#5]
挙動の問題提議です。
主に `alias touch=touch-alt` をして使っている場合、touch コマンドをタイムスタンプの更新のように使ったときに誤ってファイル内容を削除しかねないと思いました。

```
$ cat hoge.txt
something.
...

$ touch hoge.txt
$ cat hoge

$ # hoge.txt の中身が消えている
```

この挙動よりかは hoge.txt が存在していた場合は本来のようにタイムスタンプの更新をするだけにした方が良い気がしましたがどうでしょうか。

**Comment by akameco** [comment]
2つ問題があります。
- タイムスタンプの更新をサポートしようとしても、もともとのオプションが競合するため完全にサポートすることはできないこと
- タイムスタンプの変更という用途で`touch`コマンドを使うことがほぼないこと

上記から、タイムスタンプ更新の機能は今後もサポートする予定はありません。(もしタイムスタンプの機能が必要なユーザがいれば`alias`で上書きしなければいい話です)

ただ、本題である上書き回避のために、オーバーライドを抑制する挙動があってもいいかも知れません。

**Comment by akameco** [comment]
すでにオーバーライドはデフォルトで抑制していたのでクローズします。
`-o` or `--overwrite`がそれです。
